added install-protoc command from lib-gha to pkg-protobuf(v1)
make-files/pkg-protobuf pull request #11
Opened 2021-04-12 03:21 UTC by na4ma4

Replaces make-files/lib-gha#1, adds installing an artefact of the latest protoc binary (unless overridden by specifying your own `PROTOC_COMMAND`).

Although in testing, I didn't seem to need this line, but I'll test further:
```Makefile
--proto_path="$(dir $(PROTOC_COMMAND))../include" \
```

2021-04-12 21:08 UTC, jmalloc requested changes

2021-04-12 21:08 UTC, jmalloc commented on Makefile
> +artifacts/protoc/bin/protoc:
```suggestion
artifacts/protobuf/bin/protoc:
```

2021-04-12 21:08 UTC, jmalloc commented on Makefile
> +PROTOC_COMMAND ?= $(MF_PROJECT_ROOT)/artifacts/protoc/bin/protoc
```suggestion
PROTOC_COMMAND ?= $(MF_PROJECT_ROOT)/artifacts/protobuf/bin/protoc
```

2021-04-12 23:56 UTC, danilvpetrov approved these changes

2021-04-13 00:14 UTC, na4ma4 commented on Makefile
> +PROTOC_COMMAND ?= $(MF_PROJECT_ROOT)/artifacts/protoc/bin/protoc
Updated.

2021-04-13 00:14 UTC, na4ma4 commented on Makefile
> +artifacts/protoc/bin/protoc:
Updated.

2021-04-13 00:28 UTC, jmalloc approved these changes

2021-04-13 01:05 UTC, merged